### PR TITLE
Use mongo fulltext not elasticsearch

### PR DESCRIPTION
**Pull request by h-lame**
As an alternative to https://github.com/alphagov/maslow/pull/152 instead of removing search from maslow, we change need api (which powers the maslow search box) to use mongo full text search instead of relying on elasticsearch.  The need api is the last thing using the elasticsearch.backend cluster since we deployed https://github.com/alphagov/govuk-puppet/pull/4924 so this would let us turn off those machines.  There are some extra notes about the caveats for this in the commit messages.

/cc @alexmuller, @jennyd

### CODE REVIEW

**Comment by jennyd** [comment]
Text search in mongo 2.4 comes with [some red warnings](https://docs.mongodb.com/v2.4/tutorial/enable-text-search/):

screen shot 2016-10-07 at 16 29 56

This would be for our main backend mongo cluster which is used by quite a few other apps. Is upgrading mongo an option?

**Comment by h-lame** [comment]
Ah! I missed that when reading the docs for this stuff (I was mostly looking at https://docs.mongodb.com/v2.4/core/index-text/ which helpfully doesn't have the big red warning).  This doesn't seem good at all.  Perhaps not worth trying in that case.

**Comment by h-lame** [comment]
Closing this as using the experimental fulltext search on our main production mongo cluster does not seem like a good idea.  If we upgrade the cluster to 2.6+ then this branch could act as a guide for what to do.  We'd have to get rid of the migration because the feature doesn't need enabling in 2.6+.  We might want to look at how we use the `text_search` mongoid function too, as `$text` becomes a first-class citizen in 2.6+ and it might work in a standard `where` clause.

**Comment by jennyd** [comment]
We think that we may need to get all the needs into the publishing API in the next few months so that we can tag content to them using links. At that point it may make sense for everything to use the publishing API to manage needs instead of having a separate need API (effectively making Maslow a migrated backend app), and then the publishing API would be responsible for providing search. It already does that to some extent for Specialist Publisher, so maybe we don't need to find a solution to this particular problem.

**Pull request closed without merging**
